### ISSUE TITLE
Question: making data_vars related columns optional?

### ISSUE THREAD

**Issue by matentzn** [INCATools/dosdp-tools#137]
For our [use case](https://github.com/obophenotype/upheno/pull/481#issuecomment-503162359), we would like to be able to omit the necessity of a data_var column to avoid breaking every pipeline ever; right now, the way we have specified the synonym field, dosdp-tools appears to require the presence of an actual column in the dosdp file. We need to be able to evolve annotation related fields on patterns without breaking existing pipelines (i.e. add a property). Is there any way we can currently do that? @dosumis @balhoff

**Comment by dosumis** [comment]
Nico & I have discussed this.  While it is not safe to make vars that refer to OWL entities optional unless we have a system for specifying default values, it is perfectly safe to allow data_vars and data_list_vars to be optional.  I think the behaviour of DOSDP-tools should be to allow TSVs missing columns for any data_var or data_list var in a DOSDP and where columns are present to allow for empty cells.  In these cases, not annotation should be generated.  I don't think any change to the DOSDP formal spec is required for this, although we might want to extend field descriptions to clarify expected behaviour.

This has become quite urgent for uPheno.  @balhoff - how easy would this be to implement?

**Comment by matentzn** [comment]
@balhoff Sooooooorrrrryyyyyyy, buuuuuut: Were you planning to get this issue fixed soon? And [this](https://github.com/INCATools/dosdp-tools/issues/128) one? Much love. Thanks. Sorry.
