### ISSUE TITLE
Alternate reasoners?

### ISSUE THREAD

**Issue by msinclair2** [INCATools/dosdp-tools#26]
@mikebada

Are there any plans to include other reasoners soon?  I am working with an ontology that elk has trouble with in protege, but which FaCT++ reasons over just fine. I haven't looked at the source code yet, but is the choice of reasoner modular in dosdp-tools current state?  Would I be able to redirect dosdp-tools to a different reasoner on the system and add an extra argument to include it on the command line?

Thank you for any help or suggestions!

**Comment by balhoff** [comment]
It should be straightforward to add another reasoner. We have only needed ELK so far so it hasn't been a high priority. FaCT++ may introduce complication due to its native libraries, but I think I figured that out already for another project—I'll check.

However we will need to add the other reasoners as dependencies and include them in the code; you won't be able to add them dynamically right now.

**Comment by balhoff** [comment]
@msinclair2 I added HermiT and JFact: #27 

I can still look into FaCT++, but I went ahead and did these because they were easy.

**Comment by msinclair2** [comment]
@mikebada

Hi Jim,

I have never tried JFact in Protege with our ontology as it appears it is
currently not available with the latest version of Protege.  HermiT I know
will not work.  FaCT++ is the only one I know that works for sure. I asked
on the Protege user list for an updated JFact plugin to be made available
so I can test it out.  Is JFact capable of all the exact same syntactic
features as FaCT++?  If so then it might work.  Otherwise, it would be
greatly appreciated if you could integrate FaCT++ into dosdp-tools!

Michael

**Comment by msinclair2** [comment]
@mikebada

Hi Jim,

I just confirmed that JFact v.4.0.4 as a plugin in Protege succeeds in
reasoning over our ontology.  Is that the version that you have integrated
into dosdp-tools?  Previous versions (e.g. 4.0.0 and 4.0.2) do not load
successfully as plugins in the latest major version of Protege (v. 5),
though I don't know if that means they wouldn't work on our ontology in
dosdp-tools.

Thanks,
Michael

**Comment by msinclair2** [comment]
Hi Jim,

I'm encountering what appear to be classification errors in JFact that
don't occur with FaCT++. It could be a case of incompatible syntax and not
really bugs, I don't know. I've informed Ignazio, but just in case, will
you still be able to incorporate FaCT++?

Thanks,
Michael

**Comment by balhoff** [comment]
Hi @msinclair2 I can still try FaCT++ but I can't provide a firm timeline right now. I have been traveling and the next few weeks I have some deadlines to address. Thanks for your patience!

**Comment by msinclair2** [comment]
Sure, thanks Jim.

I'm now starting to play around with dosdp-tools (finally).  The
documentation and examples/tutorials are a little sparse, so I'm having
trouble figuring out what the minimal elements are to create a functional
SPARQL query.  Is there some more nuanced documentation out there that you
can point me to?

Thank you for the work you have done on this tool so far!

**Comment by balhoff** [comment]
Here's something similar to the example I had put in another issue:

```
curl -L -O https://raw.githubusercontent.com/obophenotype/upheno/master/src/patterns/abnormalSize.yaml
curl -L -O http://purl.obolibrary.org/obo/hp.owl
dosdp-tools query --ontology=hp.owl --obo-prefixes --template=abnormalSize.yaml --reasoner=ELK --print-query
```

Given that you download `abnormalSize.yaml` and `abnormalSize.tsv`, that should print a SPARQL query to the console. You don't need `--ontology=hp.owl` or `--reasoner=ELK`. You need to pass the ontology only if you want to actually run the query. You need to pass a reasoner (and an ontology) only if your variable filler constraints are OWL expressions rather than named classes. If this is the case you'll see these expressions expanded into big FILTERS for all the matching classes found by the reasoner.

You probably haven't missed any documentation. The usage output is about all there is so far.

**Comment by balhoff** [comment]
I'm going to close this since we have HermiT and JFact now and don't need native code. If FaCT++ turns out to be absolutely required, we can reopen.
