### ISSUE TITLE
Odd intepretation of 'logical axioms'

### ISSUE THREAD

**Issue by dosumis** [INCATools/dosdp-tools#39]
When I run [this pattern](https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/402c4e9b6668ad2fc4c9dd86845d30000781261e/fbbt/src/patterns/VNC_subdomain.yml) with [this tsv](https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/larval_neuropils_tracts/fbbt/src/patterns/VNC_subdomain.tsv) I get a very odd looking ontology:

![image](https://user-images.githubusercontent.com/112839/35693344-dcb8ca66-0775-11e8-8e39-a8ff6c782169.png)

The DOSDP passes basic checking with python and the build with DOSDP tools doesn't emit any errors.

I expected that each class should have all of the specified subClassOf axioms.  

In addition - something odd has happened to the annotation axioms.  They are rolled, but I can't see them on the terms in Protege.  Here's an example in functional syntax from the OWL file rolled:

AnnotationAssertion(rdfs:label <http://purl.obolibrary.org/obo/FBbt_00015072> "centrolateral neuropil of larval abdominal segment 7"^^xsd:string)
AnnotationAssertion(Annotation(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> "['PMID:28730682']"^^xsd:string) <http://purl.obolibrary.org/obo/IAO_0000115> <http://purl.obolibrary.org/obo/FBbt_00015073> "A synaptic neuropil subdomain at the intersection of centromedial subdivision of ventral nerve cord  and the larval abdominal segment 7.\"
"^^xsd:string)

**Comment by balhoff** [comment]
I'm surprised you aren't getting errors from the YAML file:
- `name` should be `pattern_name`
- `def.xrefs` should have value `def_xrefs` rather than an object with `value` key
- `long_sub_short` variable is not defined
- `type` should be `axiom_type`

Won't be an error but won't work:
- `object_properties` should be `objectProperties` or `relations`
- `owl_axioms` should be `logical_axioms`

I'm guessing you already fixed all these, since now I see what you see. :-)

**Comment by balhoff** [comment]
@dosumis this was not working correctly. Should be fixed in new release: https://github.com/INCATools/dosdp-tools/releases/tag/v0.6.1
