### ISSUE TITLE
Generate ontology of design patterns

### ISSUE THREAD

**Issue by balhoff** [INCATools/dosdp-tools#6]
Use design pattern definitions to create OWL classes in order to view subsumptions across patterns.

**Comment by balhoff** [comment]
cc @dosumis

**Comment by cmungall** [comment]
Assume the procedure is:

 - use default fillers (variable ranges)
 - create a module using SLME or similar (necessary as ranges often contain unions)
 - standard OWLAPI reasoner classification

It may be interesting to see how many patterns have a 'prototype' class.

For bonus points, how about classifying classes as instances of DPs? Instances, because classes will be subclasses of multiple Patterns-As-Classes.

**Comment by dosumis** [comment]
> For bonus points, how about classifying classes as instances of DPs? Instances, because classes will be subclasses of multiple Patterns-As-Classes.

+1

**Comment by dosumis** [comment]
By integrating with starter kit, we should be able to generate imports for this as for any other ontology.   The ideal would be a Make command that builds the ontology with import statements and generates import files.

**Comment by balhoff** [comment]
@dosumis @matentzn couple wrinkles to keep in mind for now:

* This is relying on a `pattern_iri` key at the top level of the pattern, to give an IRI to the generated class. So that needs to be present.
  * Need to make a separate pull request to spec for this key. Name could be `pattern_iri` or maybe just `iri`.
* You can pass a single pattern to the `prototype` command `template` arg and get a tiny ontology back for just that pattern, then in the Makefile merge all these together.
  * OR—you can pass a folder name for the `template` arg and it will process all `.yaml` or .yml` files in the folder into one output ontology.
